### PR TITLE
enable travis build

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by MajicDesigns** [comment]
This seems to be too specific for the majority of library users. Had you intended this to be a pull request into the main repository?

**Comment by thijstriemstra** [comment]
Yeah so it's easily to see if there are any compilation errors or not.

> This seems to be too specific for the majority of library users. 

It doesn't affect any of the library users. What do you mean?

**Comment by MajicDesigns** [comment]
This library gets downloaded dozens of times a day.
1. The majority of Arduino users do not use PlatformIO and even less use Travis-CI.
2. Any files I include need to be supported for the life of the library.

While the file can/will be ignored by the majority of users (they may not even see it), I don't want to be in a position to have to support this for the minority unless there is a really good reason to do so.

**Comment by thijstriemstra** [comment]
> The majority of Arduino users do not use PlatformIO and even less use Travis-CI.

No and they don't have to. The .travis.yml file is a perfectly normal config file for a remote service that can run unit tests and/or compilation, external users will never have to touch or worry about it. Platformio is just a tool that can run headless on a server and execute compilation. It's a code check, not an enhancement for users.

>  I don't want to be in a position to have to support this for the minority unless there is a really good reason to do so.

You're not supporting it for any users, they can't use it in their projects whatsoever.

**Comment by thijstriemstra** [comment]
any decision on this PR?

**Comment by MajicDesigns** [comment]
I have looked at this again and decided that it would not provide value for the vast majority of library users, who are extreme novices, whilst needing me to make sure it remains relevant and up-to-date for every future release. Advanced users who want to use CI will find it easy enough to create their own (additional) files or modify their own fork of this repo.

Thanks for the contribution but I won't include it in the official release.

**Pull request closed without merging**
